### ISSUE TITLE
perl: warning: Setting locale failed.

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/rootfs-images#125]
When I run `julia --project linux/package_linux.jl --arch x86_64 --no-archive` on amdci5, I see the following warning:

```
I: Base system installed successfully.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US:",
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

**Comment by DilumAluthge** [comment]
@staticfloat Are you able to reproduce this?

**Comment by staticfloat** [comment]
I get something slightly different:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings: 
        LANGUAGE = (unset), 
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"                                                                                
    are supported and installed on your system.                                                             
perl: warning: Falling back to the standard locale ("C").
```

I wonder if you have `LANGUAGE="en_US:` set in your external environment?  In any case, I don't think this is a fatal error.

**Comment by staticfloat** [comment]
This is probably due to the environment of the host leaking into the rootfs.  We should clear the `ENV`.  I'll open a PR.

**Comment by DilumAluthge** [comment]
> This is probably due to the environment of the host leaking into the rootfs. We should clear the `ENV`. I'll open a PR.

In addition to clearing the environment when we run `debootstrap`, we should probably also clear the environment when we run the `chroot` function, right?
