### ISSUE TITLE
Python_kitchen_sink fails to download few times

### ISSUE THREAD

**Issue by ven-k** [JuliaCI/rootfs-images#144]
With the following error message
```

┌ Debug: download_artifact error
--
  | │   tree_hash = SHA1("2e3570da5116e8a4de41aaaa0d8f1f67072f1d3f")
  | │   tarball_url = "https://github.com/JuliaCI/rootfs-images/releases/download/v4.11/python_latex_kitchen_sink.x86_64.tar.gz"
  | │   tarball_hash = nothing
  | │   err = HTTP/2 302 (Operation too slow. Less than 1 bytes/sec transferred the last 20 seconds) while requesting https://github.com/JuliaCI/rootfs-images/releases/download/v4.11/python_latex_kitchen_sink.x86_64.tar.gz
  | └ @ Pkg.Artifacts /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Artifacts.jl:348
  | ┌ Error: Unable to download rootfs!
  | │   treehash = "2e3570da5116e8a4de41aaaa0d8f1f67072f1d3f"
  | │   url = "https://github.com/JuliaCI/rootfs-images/releases/download/v4.11/python_latex_kitchen_sink.x86_64.tar.gz"
  | └ @ Main /etc/buildkite-agent/plugins/github-com-staticfloat-sandbox-buildkite-plugin/lib/generate_sandboxed_bash.jl:34

```
Python-kitchen-sink fails to download

The problem is very **_intermittent_** and is observed for other versions (v4.8) as well.

**Comment by DilumAluthge** [comment]
Is this a server-side problem or a client-side problem?

Could we use the Pkg server to mirror the rootfs tarballs?

**Comment by ven-k** [comment]
I had discussed about this with Elliot. It seemed like GitHub was failing to serve such a big artifact.
I got away by using `texlive-latex-extra` instead of `texlive-full` as this reduces size to ~500MB

**Comment by DilumAluthge** [comment]
If the issue is that GitHub is failing to serve the artifact, there's not really anything for us to fix in this repo.

Worst case, we can upload the artifact to S3 and cache it with Fastly.
