### ISSUE TITLE
patchelf missing from package_linux

### ISSUE THREAD

**Issue by maleadt** [JuliaCI/rootfs-images#217]
As part of PkgEval, I'm running `contrib/fixup-libgfortran.sh` (that's a good thing to do, right?), which relies on `patchelf`. That tool isn't part of the `package_linux` rootfs.

**Comment by DilumAluthge** [comment]
I'll add it. What's the name of the `apt` package that I'd need to add?

**Comment by maleadt** [comment]
Thanks. The package should just be patchelf too: https://packages.debian.org/bullseye/patchelf
