### ISSUE TITLE
Meta-issue: use our own custom `glibc` on each `*-linux-gnu` platform

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/rootfs-images#44]
- [x] #175
- [x] #176
- [x] #177
- [x] #178
- [x] #179

**Comment by DilumAluthge** [comment]
Fixed by #166 and #167?

@staticfloat

**Comment by staticfloat** [comment]
Yes, but only for `x86_64-linux-gnu` at the moment.  We're going to let that ride on Buildkite for a little bit, which will give me time to continue improving the generation process in the BB world.

**Comment by DilumAluthge** [comment]
We only need this for `x86_64-linux-gnu` and `i686-linux-gnu`, right?

**Comment by staticfloat** [comment]
No, we need it for all `glibc` platforms; `aarch64`, `armv7l` and `ppc64le` as well.  Although the situation isn't as bad on those platforms as on `x86_64` and `i686` (because it's more common to have distros with ancient glibc's on them).

**Comment by DilumAluthge** [comment]
I'm closing this issue in favor of architecture-specific issues. That way, we can close each arch-specific issue one at a time.

- https://github.com/JuliaCI/rootfs-images/issues/175
- https://github.com/JuliaCI/rootfs-images/issues/176
- https://github.com/JuliaCI/rootfs-images/issues/177
- https://github.com/JuliaCI/rootfs-images/issues/178
- https://github.com/JuliaCI/rootfs-images/issues/179

**Comment by DilumAluthge** [comment]
I guess I can leave this open as a tracking issue.
