### ISSUE TITLE
Tracking issue for JuliaLang/julia#41573

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/rootfs-images#6]
I have subdivided JuliaLang/julia#41573 into multiple PRs:

- [x] #9
- [x] #13
- [x] #10
- [x] #11
- [x] #12

**Comment by staticfloat** [comment]
You're amazing Dilum.  I'm gonna cut a new release here to get new rootfs images published!

**Comment by DilumAluthge** [comment]
https://github.com/JuliaCI/rootfs-images/releases/tag/v3.0
